# Generated by Django 4.0.5 on 2022-06-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_sensor',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Tipo do sensor'),
        ),
    ]
