# Generated by Django 4.0.5 on 2022-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESP', '0003_rename_tipo_sensor_tipo_alter_sensor_macaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='local',
            field=models.CharField(max_length=11, null=True, verbose_name='Local de Instalação'),
        ),
    ]
