# Generated by Django 4.0.5 on 2023-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='observacao',
            field=models.TextField(max_length=100, null=True, verbose_name='Observação'),
        ),
    ]
