# Generated by Django 4.0.5 on 2022-06-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['data_cadastro']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
    ]
