# Generated by Django 4.0.5 on 2022-06-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=9, verbose_name='Temperatura')),
                ('umidade', models.CharField(max_length=11, verbose_name='Umidade')),
                ('pressao', models.CharField(max_length=11, verbose_name='Pressão')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.sensor', verbose_name='Identificação do Sensor')),
            ],
        ),
    ]
