# Generated by Django 4.0.5 on 2022-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
